<?php

namespace App\Nova\Dashboards;

use App\Nova\GuestOrder;
use App\Nova\Metrics\BannerCount;
use App\Nova\Metrics\BikeSellRequestPerDay;
use App\Nova\Metrics\BrandCount;
use App\Nova\Metrics\CancelledOrder;
use App\Nova\Metrics\CategoryCount;
use App\Nova\Metrics\DeliveriedOrder;
use App\Nova\Metrics\OrderPerDay;
use App\Nova\Metrics\OrderTotalPayment;
use App\Nova\Metrics\PendingOrder;
use App\Nova\Metrics\RecentGuestOrder;
use App\Nova\Metrics\RecentOrder;
use App\Nova\Metrics\RegisteredUsers;
use App\Nova\Metrics\ShowroomPerCity;
use App\Nova\Metrics\TotalGuestOrder;
use App\Nova\Metrics\TotalProduct;
use Laravel\Nova\Cards\Help;
use Laravel\Nova\Dashboards\Main as Dashboard;

class Main extends Dashboard
{
    /**
     * Get the cards for the dashboard.
     *
     * @return array
     */
    public function cards()
    {
        return [
            new OrderPerDay(),
            new TotalGuestOrder(),
            new PendingOrder(),
            new DeliveriedOrder(),
            new CancelledOrder(),
            new RegisteredUsers(),
            (new RecentOrder())->width("1/2"),
            (new RecentGuestOrder())->width("1/2"),
        ];
    }

    public function filters()
    {
        return [];
    }


    public function name()
    {
        return "Dashboard"; // TODO: Change the autogenerated stub
    }
}
